[package]
name = "bytecode-wasm"
version = "0.1.0"
edition = "2024"


[lib] 
crate-type = ["cdylib"]

[dependencies]
bytecode_vm = { git = "https://github.com/Pybounce/bytecode_vm" }
wasm-bindgen = "0.2.106"
